load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

load("//bazel/util:pico_linker_scripts.bzl", "include_linker_script_dir")

filegroup(
    name = "rp2350_linker_script_incls",
    srcs = glob([
        "*.incl",
    ]),
)

include_linker_script_dir(
    name = "rp2350_linker_script_args",
    use_scripts = ["default_locations.ld"],
)

cc_library(
    name = "rp2350_linker_scripts",
    target_compatible_with = ["//bazel/constraint:rp2350"],
    deps = [
        "default_locations.ld",
        "rp2350_linker_script_args",
    ],
    additional_linker_inputs = [
        "rp2350_linker_script_incls",
    ],
)