if (TARGET pico_multicore AND NOT PICO_TIME_NO_ALARM_SUPPORT)
    add_executable(pico_multicore_test pico_multicore_test.c)
    target_link_libraries(pico_multicore_test PRIVATE pico_stdlib pico_test pico_multicore)
    pico_add_extra_outputs(pico_multicore_test)

    if (NOT PICO_RISCV)
        add_executable(pico_multicore_vtable_test pico_multicore_test.c)
        target_link_libraries(pico_multicore_vtable_test PRIVATE pico_stdlib pico_test pico_multicore)
        target_compile_definitions(pico_multicore_vtable_test PRIVATE PICO_VTABLE_PER_CORE=1)
        pico_add_extra_outputs(pico_multicore_vtable_test)
    endif()
endif()
