package(default_visibility = ["//visibility:public"])

load("//bazel/util:pico_linker_scripts.bzl", "include_linker_script_dir")

exports_files(
    [
        "default_locations.ld",
        "section_platform_end.ld",
    ]
)

include_linker_script_dir(
    name = "rp2350_linker_script_args",
    use_scripts = ["default_locations.ld"],
)

cc_library(
    name = "rp2350_linker_scripts",
    target_compatible_with = ["//bazel/constraint:rp2350"],
    deps = [
        "default_locations.ld",
        "section_platform_end.ld",
        "rp2350_linker_script_args",
    ],
)