#pragma once

#define SECURE_CALL_CALLBACKS_MASK 0xfedc

#define SECURE_CALL_PRINT_VALUES    ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x1)
#define SECURE_CALL_UPDATE_RETURN   ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x2)
#define SECURE_CALL_COMPLETED       ((SECURE_CALL_CALLBACKS_MASK << 16) | 0x3)
