// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.2; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------- //
// div_3_6 //
// ------- //

#define div_3_6_wrap_target 0
#define div_3_6_wrap 0
#define div_3_6_pio_version 0

static __pio_const uint16_t div_3_6_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program div_3_6_program = {
    .instructions = div_3_6_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = div_3_6_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config div_3_6_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + div_3_6_wrap_target, offset + div_3_6_wrap);
    sm_config_set_clkdiv_int_frac(&c, 3, 153);
    return c;
}
#endif

// ------- //
// div_2_5 //
// ------- //

#define div_2_5_wrap_target 0
#define div_2_5_wrap 0
#define div_2_5_pio_version 0

static __pio_const uint16_t div_2_5_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program div_2_5_program = {
    .instructions = div_2_5_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = div_2_5_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config div_2_5_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + div_2_5_wrap_target, offset + div_2_5_wrap);
    sm_config_set_clkdiv_int_frac(&c, 2, 128);
    return c;
}
#endif

// ------ //
// div_50 //
// ------ //

#define div_50_wrap_target 0
#define div_50_wrap 0
#define div_50_pio_version 0

static __pio_const uint16_t div_50_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program div_50_program = {
    .instructions = div_50_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = div_50_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config div_50_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + div_50_wrap_target, offset + div_50_wrap);
    sm_config_set_clkdiv_int_frac(&c, 50, 0);
    return c;
}
#endif

// ----- //
// div_1 //
// ----- //

#define div_1_wrap_target 0
#define div_1_wrap 0
#define div_1_pio_version 0

static __pio_const uint16_t div_1_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program div_1_program = {
    .instructions = div_1_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = div_1_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config div_1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + div_1_wrap_target, offset + div_1_wrap);
    return c;
}
#endif

