# Runs pioasm on an input file and compares the generated output against a
# checked-in expected file. The line carrying the pioasm version string is
# ignored so the expected files do not need updating on every release.
#
# Invoked by add_test() in test/CMakeLists.txt as:
#   cmake -DPIOASM=<exe> -DINPUT=<file.pio> -DFORMAT=<output format>
#         -DEXPECTED=<expected file> -DOUTPUT=<file to write> -P compare_output.cmake

foreach(var PIOASM INPUT FORMAT EXPECTED OUTPUT)
    if (NOT DEFINED ${var})
        message(FATAL_ERROR "${var} must be defined")
    endif()
endforeach()

execute_process(
    COMMAND "${PIOASM}" -o "${FORMAT}" "${INPUT}" "${OUTPUT}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)
if (NOT result EQUAL 0)
    message(FATAL_ERROR "pioasm failed (exit code ${result}) on ${INPUT}:\n${stdout}${stderr}")
endif()

# Normalise line endings and drop the version line before comparing.
function(normalise_output in_file out_var)
    file(READ "${in_file}" contents)
    string(REPLACE "\r\n" "\n" contents "${contents}")
    string(REGEX REPLACE "[^\n]*(autogenerated by pioasm version|\"pioASMVersion\")[^\n]*\n" "" contents "${contents}")
    set(${out_var} "${contents}" PARENT_SCOPE)
endfunction()

normalise_output("${OUTPUT}" actual)
normalise_output("${EXPECTED}" expected)

if (NOT actual STREQUAL expected)
    message(FATAL_ERROR
        "pioasm '${FORMAT}' output for ${INPUT} does not match ${EXPECTED}\n"
        "Actual output was written to ${OUTPUT}\n"
        "--- expected ---\n${expected}\n--- actual ---\n${actual}")
endif()
