load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:defs.bzl", "compatible_with_rp2", "incompatible_with_config")
load("//bazel/util:transition.bzl", "extra_copts_for_all_deps")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "low_power_test_common",
    hdrs = ["low_power_test_common.h"],
    includes = ["."],
    deps = [
        "//src/rp2_common/pico_low_power",
        "//src/rp2_common/pico_status_led",
        "//src/rp2_common/pico_stdlib",
    ],
)

cc_binary(
    name = "low_power_test_timers",
    testonly = True,
    srcs = ["low_power_test_timers.c"],
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "low_power_test_common",
    ],
)

cc_binary(
    name = "low_power_test_persistent_actual",
    testonly = True,
    srcs = ["low_power_test_persistent.c"],
    tags = ["manual"],
    deps = [
        "low_power_test_common",
    ],
)

extra_copts_for_all_deps(
    name = "low_power_test_persistent",
    testonly = True,
    src = ":low_power_test_persistent_actual",
    extra_copts = [
        "-DPICO_LOW_POWER_PERSISTENT_PSTATE_STATIC=0",
    ],
    target_compatible_with = compatible_with_rp2() + incompatible_with_config("//bazel/constraint:rp2040"),
)

cc_binary(
    name = "low_power_test_gpio",
    testonly = True,
    srcs = ["low_power_test_gpio.c"],
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "low_power_test_common",
    ],
)

cc_binary(
    name = "low_power_test_timers_gpio",
    testonly = True,
    srcs = ["low_power_test_timers_gpio.c"],
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "low_power_test_common",
    ],
)

cc_binary(
    name = "low_power_test_simple",
    testonly = True,
    srcs = ["low_power_test_simple.c"],
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "low_power_test_common",
    ],
)

cc_binary(
    name = "external_sleep_timer",
    testonly = True,
    srcs = ["external_sleep_timer.c"],
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "low_power_test_common",
    ],
)
