load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:defs.bzl", "compatible_with_rp2")
load("//bazel/util:pico_linker_scripts.bzl", "include_linker_script_dir")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "rp2_linker_script_incls",
    srcs = glob([
        "*.incl",
    ]),
)

include_linker_script_dir(
    name = "rp2_linker_script_args",
)

cc_library(
    name = "rp2_linker_scripts",
    target_compatible_with = compatible_with_rp2(),
    deps = [
        "rp2_linker_script_args",
    ],
    additional_linker_inputs = [
        "rp2_linker_script_incls",
    ]
)