name: Check RISCV Flag Choices
on:
  push:
    branches-ignore:
      - 'iar/**'
  pull_request:

jobs:
  test:
    # cannot specify filter for pull_request in on: above, so do it here
    if: github.repository_owner == 'raspberrypi' && (github.event_name != 'pull_request' || !startsWith(github.head_ref, 'iar/'))
    runs-on:
    - self-hosted
    - Linux
    - X64

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check RISCV GCC 16.1.0 gives cpu=hazard3-rp2350
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        cd ${{ github.workspace }}
        mkdir -p build && rm -rf build/* && cd build
        cmake ../ -DPICO_NO_PICOTOOL=1 -DPICO_PLATFORM=rp2350-riscv -DPICO_TOOLCHAIN_PATH=/opt/riscv/gcc-riscv-32-pico-elf-16.1.0
        cat CMakeCache.txt | grep "CMAKE_ASM_FLAGS"
        cat CMakeCache.txt | grep "cpu=hazard3-rp2350"

    - name: Check RISCV GCC 15.1.0 gives arch=rv32ima_zicsr_zifencei_zba_zbb_zbs_zbkb_zca_zcb_zcmp
      if: ${{ !cancelled() }}
      run: |
        cd ${{ github.workspace }}
        mkdir -p build && rm -rf build/* && cd build
        cmake ../ -DPICO_NO_PICOTOOL=1 -DPICO_PLATFORM=rp2350-riscv -DPICO_TOOLCHAIN_PATH=/opt/riscv/riscv32-unknown-elf-gcc-15.1.0
        cat CMakeCache.txt | grep "CMAKE_ASM_FLAGS"
        cat CMakeCache.txt | grep "arch=rv32ima_zicsr_zifencei_zba_zbb_zbs_zbkb_zca_zcb_zcmp"
    
    - name: Check RISCV GCC 14.1.0 gives arch=rv32imac_zicsr_zifencei_zba_zbb_zbs_zbkb
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        cd ${{ github.workspace }}
        mkdir -p build && rm -rf build/* && cd build
        cmake ../ -DPICO_NO_PICOTOOL=1 -DPICO_PLATFORM=rp2350-riscv -DPICO_TOOLCHAIN_PATH=/opt/riscv/riscv32-unknown-elf-gcc-14.1.0
        cat CMakeCache.txt | grep "CMAKE_ASM_FLAGS"
        cat CMakeCache.txt | grep "arch=rv32imac_zicsr_zifencei_zba_zbb_zbs_zbkb"

    - name: Check RISCV GCC 12.1.0 gives arch=rv32imac_zicsr_zifencei_zba_zbb_zbs_zbkb
      if: ${{ !cancelled() }}
      run: |
        cd ${{ github.workspace }}
        mkdir -p build && rm -rf build/* && cd build
        cmake ../ -DPICO_NO_PICOTOOL=1 -DPICO_PLATFORM=rp2350-riscv -DPICO_TOOLCHAIN_PATH=/opt/riscv/riscv32-unknown-elf-gcc-12.1.0
        cat CMakeCache.txt | grep "CMAKE_ASM_FLAGS"
        cat CMakeCache.txt | grep "arch=rv32imac_zicsr_zifencei_zba_zbb_zbs_zbkb"
